### PR TITLE
Add Fastlane metadata structure

### PR DESCRIPTION
**Pull request by licaon-kter**
Please squash commits on merge

After merge do Tag an actual release so we can merge on F-Droid too.

Ref: https://github.com/mgerdes/Open-Golf/issues/7

### CODE REVIEW

**Comment by licaon-kter** [comment]
Any blockers?

**Comment by licaon-kter** [comment]
I'd like to bring this to F-Droid.

**Comment by shuvashish76** [comment]
@mgerdes any updates? Seems F-Droid [merge request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10813) is almost ready.😇

Edit : Inactive since last 2months, I hope you're doing good in personal life.

**Comment by Korb** [comment]
@mgerdes, @geoffbeier, what was the difficulty here? I'd like to translate the F-Droid app description into my language, but without the `Fastlane`-structure in your project, the only way I can do this is through a PR to `F-Droid` (which I'd prefer not to do).

**Pull request closed without merging**
